export const mappingForMissingCountryNames: Record<string, string> = {
  "Antigua And Barbuda": "Antigua and Barbuda",
  "Bonaire, Sint Eustatius and Saba": "Caribbean Netherlands",
  China: "People's Republic of China",
  "Cote D'Ivoire (Ivory Coast)": "Ivory Coast",
  "Fiji Islands": "Fiji",
  "Gambia The": "The Gambia",
  "Hong Kong S.A.R.": "Hong Kong",
  Ireland: "Republic of Ireland",
  Micronesia: "Federated States of Micronesia",
  "Papua new Guinea": "Papua New Guinea",
  "Saint Kitts And Nevis": "Saint Kitts and Nevis",
  "Saint Vincent And The Grenadines": "Saint Vincent and the Grenadines",
  "Sao Tome and Principe": "São Tomé and Príncipe",
  Swaziland: "Eswatini",
  "Trinidad And Tobago": "Trinidad and Tobago",
  "United States": "United States of America",
  "Virgin Islands (US)": "Virgin Islands",
  "Palestine, State of": "State of Palestine",
  "Aland Islands": "Åland Islands",
  "Saint Martin (French part)": "Saint-Martin",
  "Virgin Islands (British)": "British Virgin Islands",
  "Cocos (Keeling) Islands": "Cocos Islands",
  "Saint Barthelemy": "Saint Barthélemy",
  "Falkland Islands [Malvinas]": "Falkland Islands",
  "Sint Maarten (Dutch part)": "Sint Maarten",
};
