export const CITY_NAMES_EN_TO_TR: Record<string, string> = {
  Istanbul: "İstanbul",
  Izmir: "İzmir",
  Kahramanmaras: "Kahramanmaraş",
  Kutahya: "Kütahya",
  Canakkale: "Çanakkale",
  Nigde: "Niğde",
  Diyarbakir: "Diyarbakır",
  Sanliurfa: "Şanlıurfa",
  Sirnak: "Şırnak",
  Aydin: "Aydın",
  Mugla: "Muğla",
  Elazig: "Elazığ",
  Nevsehir: "Nevşehir",
  Duzce: "Düzce",
  Corum: "Çorum",
  Gumushane: "Gümüşhane",
  Eskisehir: "Eskişehir",
  Tekirdag: "Tekirdağ",
  Agri: "Ağrı",
  Kirikkale: "Kırıkkale",
  Adiyaman: "Adıyaman",
  Usak: "Uşak",
  Balikesir: "Balıkesir",
  Bingol: "Bingöl",
  Karabuk: "Karabük",
  Cankiri: "Çankırı",
  Bartin: "Bartın",
  Kirsehir: "Kırşehir",
  Kirklareli: "Kırklareli",
  Mus: "Muş",
  Igdir: "Iğdır",
};

const TurkeyMap: Record<string, string[]> = {
  adana: [
    "ALADAĞ",
    "CEYHAN",
    "ÇUKUROVA",
    "FEKE",
    "İMAMOĞLU",
    "KARAİSALI",
    "KARATAŞ",
    "KOZAN",
    "POZANTI",
    "SAİMBEYLİ",
    "SARIÇAM",
    "SEYHAN",
    "TUFANBEYLİ",
    "YUMURTALIK",
    "YÜREĞİR",
  ],
  adıyaman: [
    "adıyaman",
    "BESNİ",
    "ÇELİKHAN",
    "GERGER",
    "GÖLBAŞI",
    "KAHTA",
    "SAMSAT",
    "SİNCİK",
    "TUT",
  ],
  afyonkarahisar: [
    "afyonkarahisar",
    "BAŞMAKÇI",
    "BAYAT",
    "BOLVADİN",
    "ÇAY",
    "ÇOBANLAR",
    "DAZKIRI",
    "DİNAR",
    "EMİRDAĞ",
    "EVCİLER",
    "HOCALAR",
    "İHSANİYE",
    "İSCEHİSAR",
    "KIZILÖREN",
    "SANDIKLI",
    "SİNANPAŞA",
    "SULTANDAĞI",
    "ŞUHUT",
  ],
  ağrı: [
    "ağrı",
    "DİYADİN",
    "DOĞUBAYAZIT",
    "ELEŞKİRT",
    "HAMUR",
    "PATNOS",
    "TAŞLIÇAY",
    "TUTAK",
  ],
  amasya: [
    "amasya",
    "GÖYNÜCEK",
    "GÜMÜŞHACIKÖY",
    "HAMAMÖZÜ",
    "MERZİFON",
    "SULUOVA",
    "TAŞOVA",
  ],
  ankara: [
    "AKYURT",
    "ALTINDAĞ",
    "AYAŞ",
    "BALA",
    "BEYPAZARI",
    "ÇAMLIDERE",
    "ÇANKAYA",
    "ÇUBUK",
    "ELMADAĞ",
    "ETİMESGUT",
    "EVREN",
    "GÖLBAŞI",
    "GÜDÜL",
    "HAYMANA",
    "KAHRAMANKAZAN",
    "KALECİK",
    "KEÇİÖREN",
    "KIZILCAHAMAM",
    "MAMAK",
    "NALLIHAN",
    "POLATLI",
    "PURSAKLAR",
    "SİNCAN",
    "ŞEREFLİKOÇHİSAR",
    "YENİMAHALLE",
  ],
  antalya: [
    "AKSEKİ",
    "AKSU",
    "ALANYA",
    "DEMRE",
    "DÖŞEMEALTI",
    "ELMALI",
    "FİNİKE",
    "GAZİPAŞA",
    "GÜNDOĞMUŞ",
    "İBRADI",
    "KAŞ",
    "KEMER",
    "KEPEZ",
    "KONYAALTI",
    "KORKUTELİ",
    "KUMLUCA",
    "MANAVGAT",
    "MURATPAŞA",
    "SERİK",
  ],
  artvin: [
    "artvin",
    "ARDANUÇ",
    "ARHAVİ",
    "BORÇKA",
    "HOPA",
    "KEMALPAŞA",
    "MURGUL",
    "ŞAVŞAT",
    "YUSUFELİ",
  ],
  aydın: [
    "BOZDOĞAN",
    "BUHARKENT",
    "ÇİNE",
    "DİDİM",
    "EFELER",
    "GERMENCİK",
    "İNCİRLİOVA",
    "KARACASU",
    "KARPUZLU",
    "KOÇARLI",
    "KÖŞK",
    "KUŞADASI",
    "KUYUCAK",
    "NAZİLLİ",
    "SÖKE",
    "SULTANHİSAR",
    "YENİPAZAR",
  ],
  balıkesir: [
    "ALTIEYLÜL",
    "AYVALIK",
    "BALYA",
    "BANDIRMA",
    "BİGADİÇ",
    "BURHANİYE",
    "DURSUNBEY",
    "EDREMİT",
    "ERDEK",
    "GÖMEÇ",
    "GÖNEN",
    "HAVRAN",
    "İVRİNDİ",
    "KARESİ",
    "KEPSUT",
    "MANYAS",
    "MARMARA",
    "SAVAŞTEPE",
    "SINDIRGI",
    "SUSURLUK",
  ],
  bilecik: [
    "bilecik",
    "BOZÜYÜK",
    "GÖLPAZARI",
    "İNHİSAR",
    "OSMANELİ",
    "PAZARYERİ",
    "SÖĞÜT",
    "YENİPAZAR",
  ],
  bingöl: [
    "bingöl",
    "ADAKLI",
    "GENÇ",
    "KARLIOVA",
    "KİĞI",
    "SOLHAN",
    "YAYLADERE",
    "YEDİSU",
  ],
  bitlis: [
    "bitlis",
    "ADİLCEVAZ",
    "AHLAT",
    "GÜROYMAK",
    "HİZAN",
    "MUTKİ",
    "TATVAN",
  ],
  bolu: [
    "bolu",
    "DÖRTDİVAN",
    "GEREDE",
    "GÖYNÜK",
    "KIBRISCIK",
    "MENGEN",
    "MUDURNU",
    "SEBEN",
    "YENİÇAĞA",
  ],
  burdur: [
    "burdur",
    "AĞLASUN",
    "ALTINYAYLA",
    "BUCAK",
    "ÇAVDIR",
    "ÇELTİKÇİ",
    "GÖLHİSAR",
    "KARAMANLI",
    "KEMER",
    "TEFENNİ",
    "YEŞİLOVA",
  ],
  bursa: [
    "BÜYÜKORHAN",
    "GEMLİK",
    "GÜRSU",
    "HARMANCIK",
    "İNEGÖL",
    "İZNİK",
    "KARACABEY",
    "KELES",
    "KESTEL",
    "MUDANYA",
    "MUSTAFAKEMALPAŞA",
    "NİLÜFER",
    "ORHANELİ",
    "ORHANGAZİ",
    "OSMANGAZİ",
    "YENİŞEHİR",
    "YILDIRIM",
  ],
  çanakkale: [
    "çanakkale",
    "AYVACIK",
    "BAYRAMİÇ",
    "BİGA",
    "BOZCAADA",
    "ÇAN",
    "ECEABAT",
    "EZİNE",
    "GELİBOLU",
    "GÖKÇEADA",
    "LAPSEKİ",
    "YENİCE",
  ],
  çankırı: [
    "çankırı",
    "ATKARACALAR",
    "BAYRAMÖREN",
    "ÇERKEŞ",
    "ELDİVAN",
    "ILGAZ",
    "KIZILIRMAK",
    "KORGUN",
    "KURŞUNLU",
    "ORTA",
    "ŞABANÖZÜ",
    "YAPRAKLI",
  ],
  çorum: [
    "çorum",
    "ALACA",
    "BAYAT",
    "BOĞAZKALE",
    "DODURGA",
    "İSKİLİP",
    "KARGI",
    "LAÇİN",
    "MECİTÖZÜ",
    "OĞUZLAR",
    "ORTAKÖY",
    "OSMANCIK",
    "SUNGURLU",
    "UĞURLUDAĞ",
  ],
  denizli: [
    "ACIPAYAM",
    "BABADAĞ",
    "BAKLAN",
    "BEKİLLİ",
    "BEYAĞAÇ",
    "BOZKURT",
    "BULDAN",
    "ÇAL",
    "ÇAMELİ",
    "ÇARDAK",
    "ÇİVRİL",
    "GÜNEY",
    "HONAZ",
    "KALE",
    "MERKEZEFENDİ",
    "PAMUKKALE",
    "SARAYKÖY",
    "SERİNHİSAR",
    "TAVAS",
  ],
  diyarbakır: [
    "BAĞLAR",
    "BİSMİL",
    "ÇERMİK",
    "ÇINAR",
    "ÇÜNGÜŞ",
    "DİCLE",
    "EĞİL",
    "ERGANİ",
    "HANİ",
    "HAZRO",
    "KAYAPINAR",
    "KOCAKÖY",
    "KULP",
    "LİCE",
    "SİLVAN",
    "SUR",
    "YENİŞEHİR",
  ],
  edirne: [
    "edirne",
    "ENEZ",
    "HAVSA",
    "İPSALA",
    "KEŞAN",
    "LALAPAŞA",
    "MERİÇ",
    "SÜLOĞLU",
    "UZUNKÖPRÜ",
  ],
  elazığ: [
    "elazığ",
    "AĞIN",
    "ALACAKAYA",
    "ARICAK",
    "BASKİL",
    "KARAKOÇAN",
    "KEBAN",
    "KOVANCILAR",
    "MADEN",
    "PALU",
    "SİVRİCE",
  ],
  erzincan: [
    "erzincan",
    "ÇAYIRLI",
    "İLİÇ",
    "KEMAH",
    "KEMALİYE",
    "OTLUKBELİ",
    "REFAHİYE",
    "TERCAN",
    "ÜZÜMLÜ",
  ],
  erzurum: [
    "AŞKALE",
    "AZİZİYE",
    "ÇAT",
    "HINIS",
    "HORASAN",
    "İSPİR",
    "KARAÇOBAN",
    "KARAYAZI",
    "KÖPRÜKÖY",
    "NARMAN",
    "OLTU",
    "OLUR",
    "PALANDÖKEN",
    "PASİNLER",
    "PAZARYOLU",
    "ŞENKAYA",
    "TEKMAN",
    "TORTUM",
    "UZUNDERE",
    "YAKUTİYE",
  ],
  eskişehir: [
    "ALPU",
    "BEYLİKOVA",
    "ÇİFTELER",
    "GÜNYÜZÜ",
    "HAN",
    "İNÖNÜ",
    "MAHMUDİYE",
    "MİHALGAZİ",
    "MİHALIÇÇIK",
    "ODUNPAZARI",
    "SARICAKAYA",
    "SEYİTGAZİ",
    "SİVRİHİSAR",
    "TEPEBAŞI",
  ],
  gaziantep: [
    "ARABAN",
    "İSLAHİYE",
    "KARKAMIŞ",
    "NİZİP",
    "NURDAĞI",
    "OĞUZELİ",
    "ŞAHİNBEY",
    "ŞEHİTKAMİL",
    "YAVUZELİ",
  ],
  giresun: [
    "giresun",
    "ALUCRA",
    "BULANCAK",
    "ÇAMOLUK",
    "ÇANAKÇI",
    "DERELİ",
    "DOĞANKENT",
    "ESPİYE",
    "EYNESİL",
    "GÖRELE",
    "GÜCE",
    "KEŞAP",
    "PİRAZİZ",
    "ŞEBİNKARAHİSAR",
    "TİREBOLU",
    "YAĞLIDERE",
  ],
  gümüşhane: ["gümüşhane", "KELKİT", "KÖSE", "KÜRTÜN", "ŞİRAN", "TORUL"],
  hakkari: ["hakkari", "ÇUKURCA", "DERECİK", "ŞEMDİNLİ", "YÜKSEKOVA"],
  hatay: [
    "ALTINÖZÜ",
    "ANTAKYA",
    "ARSUZ",
    "BELEN",
    "DEFNE",
    "DÖRTYOL",
    "ERZİN",
    "HASSA",
    "İSKENDERUN",
    "KIRIKHAN",
    "KUMLU",
    "PAYAS",
    "REYHANLI",
    "SAMANDAĞ",
    "YAYLADAĞI",
  ],
  ısparta: [
    "ısparta",
    "AKSU",
    "ATABEY",
    "EĞİRDİR",
    "GELENDOST",
    "GÖNEN",
    "KEÇİBORLU",
    "SENİRKENT",
    "SÜTÇÜLER",
    "ŞARKİKARAAĞAÇ",
    "ULUBORLU",
    "YALVAÇ",
    "YENİŞARBADEMLİ",
  ],
  mersin: [
    "AKDENİZ",
    "ANAMUR",
    "AYDINCIK",
    "BOZYAZI",
    "ÇAMLIYAYLA",
    "ERDEMLİ",
    "GÜLNAR",
    "MEZİTLİ",
    "MUT",
    "SİLİFKE",
    "TARSUS",
    "TOROSLAR",
    "YENİŞEHİR",
  ],
  istanbul: [
    "ADALAR",
    "ARNAVUTKÖY",
    "ATAŞEHİR",
    "AVCILAR",
    "BAĞCILAR",
    "BAHÇELİEVLER",
    "BAKIRKÖY",
    "BAŞAKŞEHİR",
    "BAYRAMPAŞA",
    "BEŞİKTAŞ",
    "BEYKOZ",
    "BEYLİKDÜZÜ",
    "BEYOĞLU",
    "BÜYÜKÇEKMECE",
    "ÇATALCA",
    "ÇEKMEKÖY",
    "ESENLER",
    "ESENYURT",
    "EYÜPSULTAN",
    "FATİH",
    "GAZİOSMANPAŞA",
    "GÜNGÖREN",
    "KADIKÖY",
    "KAĞITHANE",
    "KARTAL",
    "KÜÇÜKÇEKMECE",
    "MALTEPE",
    "PENDİK",
    "SANCAKTEPE",
    "SARIYER",
    "SİLİVRİ",
    "SULTANBEYLİ",
    "SULTANGAZİ",
    "ŞİLE",
    "ŞİŞLİ",
    "TUZLA",
    "ÜMRANİYE",
    "ÜSKÜDAR",
    "ZEYTİNBURNU",
  ],
  izmir: [
    "ALİAĞA",
    "BALÇOVA",
    "BAYINDIR",
    "BAYRAKLI",
    "BERGAMA",
    "BEYDAĞ",
    "BORNOVA",
    "BUCA",
    "ÇEŞME",
    "ÇİĞLİ",
    "DİKİLİ",
    "FOÇA",
    "GAZİEMİR",
    "GÜZELBAHÇE",
    "KARABAĞLAR",
    "KARABURUN",
    "KARŞIYAKA",
    "KEMALPAŞA",
    "KINIK",
    "KİRAZ",
    "KONAK",
    "MENDERES",
    "MENEMEN",
    "NARLIDERE",
    "ÖDEMİŞ",
    "SEFERİHİSAR",
    "SELÇUK",
    "TİRE",
    "TORBALI",
    "URLA",
  ],
  kars: [
    "kars",
    "AKYAKA",
    "ARPAÇAY",
    "DİGOR",
    "KAĞIZMAN",
    "SARIKAMIŞ",
    "SELİM",
    "SUSUZ",
  ],
  kastamonu: [
    "kastamonu",
    "ABANA",
    "AĞLI",
    "ARAÇ",
    "AZDAVAY",
    "BOZKURT",
    "CİDE",
    "ÇATALZEYTİN",
    "DADAY",
    "DEVREKANİ",
    "DOĞANYURT",
    "HANÖNÜ",
    "İHSANGAZİ",
    "İNEBOLU",
    "KÜRE",
    "PINARBAŞI",
    "SEYDİLER",
    "ŞENPAZAR",
    "TAŞKÖPRÜ",
    "TOSYA",
  ],
  kayseri: [
    "AKKIŞLA",
    "BÜNYAN",
    "DEVELİ",
    "FELAHİYE",
    "HACILAR",
    "İNCESU",
    "KOCASİNAN",
    "MELİKGAZİ",
    "ÖZVATAN",
    "PINARBAŞI",
    "SARIOĞLAN",
    "SARIZ",
    "TALAS",
    "TOMARZA",
    "YAHYALI",
    "YEŞİLHİSAR",
  ],
  kırklareli: [
    "kırklareli",
    "BABAESKİ",
    "DEMİRKÖY",
    "KOFÇAZ",
    "LÜLEBURGAZ",
    "PEHLİVANKÖY",
    "PINARHİSAR",
    "VİZE",
  ],
  kırşehir: [
    "kırşehir",
    "AKÇAKENT",
    "AKPINAR",
    "BOZTEPE",
    "ÇİÇEKDAĞI",
    "KAMAN",
    "MUCUR",
  ],
  kocaeli: [
    "BAŞİSKELE",
    "ÇAYIROVA",
    "DARICA",
    "DERİNCE",
    "DİLOVASI",
    "GEBZE",
    "GÖLCÜK",
    "İZMİT",
    "KANDIRA",
    "KARAMÜRSEL",
    "KARTEPE",
    "KÖRFEZ",
  ],
  konya: [
    "AHIRLI",
    "AKÖREN",
    "AKŞEHİR",
    "ALTINEKİN",
    "BEYŞEHİR",
    "BOZKIR",
    "CİHANBEYLİ",
    "ÇELTİK",
    "ÇUMRA",
    "DERBENT",
    "DEREBUCAK",
    "DOĞANHİSAR",
    "EMİRGAZİ",
    "EREĞLİ",
    "GÜNEYSINIR",
    "HADİM",
    "HALKAPINAR",
    "HÜYÜK",
    "ILGIN",
    "KADINHANI",
    "KARAPINAR",
    "KARATAY",
    "KULU",
    "MERAM",
    "SARAYÖNÜ",
    "SELÇUKLU",
    "SEYDİŞEHİR",
    "TAŞKENT",
    "TUZLUKÇU",
    "YALIHÜYÜK",
    "YUNAK",
  ],
  kütahya: [
    "kütahya",
    "ALTINTAŞ",
    "ASLANAPA",
    "ÇAVDARHİSAR",
    "DOMANİÇ",
    "DUMLUPINAR",
    "EMET",
    "GEDİZ",
    "HİSARCIK",
    "PAZARLAR",
    "SİMAV",
    "ŞAPHANE",
    "TAVŞANLI",
  ],
  malatya: [
    "AKÇADAĞ",
    "ARAPGİR",
    "ARGUVAN",
    "BATTALGAZİ",
    "DARENDE",
    "DOĞANŞEHİR",
    "DOĞANYOL",
    "HEKİMHAN",
    "KALE",
    "KULUNCAK",
    "PÜTÜRGE",
    "YAZIHAN",
    "YEŞİLYURT",
  ],
  manisa: [
    "AHMETLİ",
    "AKHİSAR",
    "ALAŞEHİR",
    "DEMİRCİ",
    "GÖLMARMARA",
    "GÖRDES",
    "KIRKAĞAÇ",
    "KÖPRÜBAŞI",
    "KULA",
    "SALİHLİ",
    "SARIGÖL",
    "SARUHANLI",
    "SELENDİ",
    "SOMA",
    "ŞEHZADELER",
    "TURGUTLU",
    "YUNUSEMRE",
  ],
  kahramanmaraş: [
    "AFŞİN",
    "ANDIRIN",
    "ÇAĞLAYANCERİT",
    "DULKADİROĞLU",
    "EKİNÖZÜ",
    "ELBİSTAN",
    "GÖKSUN",
    "NURHAK",
    "ONİKİŞUBAT",
    "PAZARCIK",
    "TÜRKOĞLU",
  ],
  mardin: [
    "ARTUKLU",
    "DARGEÇİT",
    "DERİK",
    "KIZILTEPE",
    "MAZIDAĞI",
    "MİDYAT",
    "NUSAYBİN",
    "ÖMERLİ",
    "SAVUR",
    "YEŞİLLİ",
  ],
  muğla: [
    "BODRUM",
    "DALAMAN",
    "DATÇA",
    "FETHİYE",
    "KAVAKLIDERE",
    "KÖYCEĞİZ",
    "MARMARİS",
    "MENTEŞE",
    "MİLAS",
    "ORTACA",
    "SEYDİKEMER",
    "ULA",
    "YATAĞAN",
  ],
  muş: ["muş", "BULANIK", "HASKÖY", "KORKUT", "MALAZGİRT", "VARTO"],
  nevşehir: [
    "nevşehir",
    "ACIGÖL",
    "AVANOS",
    "DERİNKUYU",
    "GÜLŞEHİR",
    "HACIBEKTAŞ",
    "KOZAKLI",
    "ÜRGÜP",
  ],
  niğde: ["niğde", "ALTUNHİSAR", "BOR", "ÇAMARDI", "ÇİFTLİK", "ULUKIŞLA"],
  ordu: [
    "AKKUŞ",
    "ALTINORDU",
    "AYBASTI",
    "ÇAMAŞ",
    "ÇATALPINAR",
    "ÇAYBAŞI",
    "FATSA",
    "GÖLKÖY",
    "GÜLYALI",
    "GÜRGENTEPE",
    "İKİZCE",
    "KABADÜZ",
    "KABATAŞ",
    "KORGAN",
    "KUMRU",
    "MESUDİYE",
    "PERŞEMBE",
    "ULUBEY",
    "ÜNYE",
  ],
  rize: [
    "rize",
    "ARDEŞEN",
    "ÇAMLIHEMŞİN",
    "ÇAYELİ",
    "DEREPAZARI",
    "FINDIKLI",
    "GÜNEYSU",
    "HEMŞİN",
    "İKİZDERE",
    "İYİDERE",
    "KALKANDERE",
    "PAZAR",
  ],
  sakarya: [
    "ADAPAZARI",
    "AKYAZI",
    "ARİFİYE",
    "ERENLER",
    "FERİZLİ",
    "GEYVE",
    "HENDEK",
    "KARAPÜRÇEK",
    "KARASU",
    "KAYNARCA",
    "KOCAALİ",
    "PAMUKOVA",
    "SAPANCA",
    "SERDİVAN",
    "SÖĞÜTLÜ",
    "TARAKLI",
  ],
  samsun: [
    "ALAÇAM",
    "ASARCIK",
    "ATAKUM",
    "AYVACIK",
    "BAFRA",
    "CANİK",
    "ÇARŞAMBA",
    "HAVZA",
    "İLKADIM",
    "KAVAK",
    "LADİK",
    "19 MAYIS",
    "SALIPAZARI",
    "TEKKEKÖY",
    "TERME",
    "VEZİRKÖPRÜ",
    "YAKAKENT",
  ],
  siirt: ["siirt", "BAYKAN", "ERUH", "KURTALAN", "PERVARİ", "ŞİRVAN", "TİLLO"],
  sinop: [
    "sinop",
    "AYANCIK",
    "BOYABAT",
    "DİKMEN",
    "DURAĞAN",
    "ERFELEK",
    "GERZE",
    "SARAYDÜZÜ",
    "TÜRKELİ",
  ],
  sivas: [
    "sivas",
    "AKINCILAR",
    "ALTINYAYLA",
    "DİVRİĞİ",
    "DOĞANŞAR",
    "GEMEREK",
    "GÖLOVA",
    "GÜRÜN",
    "HAFİK",
    "İMRANLI",
    "KANGAL",
    "KOYULHİSAR",
    "SUŞEHRİ",
    "ŞARKIŞLA",
    "ULAŞ",
    "YILDIZELİ",
    "ZARA",
  ],
  tekirdağ: [
    "ÇERKEZKÖY",
    "ÇORLU",
    "ERGENE",
    "HAYRABOLU",
    "KAPAKLI",
    "MALKARA",
    "MARMARAEREĞLİSİ",
    "MURATLI",
    "SARAY",
    "SÜLEYMANPAŞA",
    "ŞARKÖY",
  ],
  tokat: [
    "tokat",
    "ALMUS",
    "ARTOVA",
    "BAŞÇİFTLİK",
    "ERBAA",
    "NİKSAR",
    "PAZAR",
    "REŞADİYE",
    "SULUSARAY",
    "TURHAL",
    "YEŞİLYURT",
    "ZİLE",
  ],
  trabzon: [
    "AKÇAABAT",
    "ARAKLI",
    "ARSİN",
    "BEŞİKDÜZÜ",
    "ÇARŞIBAŞI",
    "ÇAYKARA",
    "DERNEKPAZARI",
    "DÜZKÖY",
    "HAYRAT",
    "KÖPRÜBAŞI",
    "MAÇKA",
    "OF",
    "ORTAHİSAR",
    "SÜRMENE",
    "ŞALPAZARI",
    "TONYA",
    "VAKFIKEBİR",
    "YOMRA",
  ],
  tunceli: [
    "tunceli",
    "ÇEMİŞGEZEK",
    "HOZAT",
    "MAZGİRT",
    "NAZIMİYE",
    "OVACIK",
    "PERTEK",
    "PÜLÜMÜR",
  ],
  şanlıurfa: [
    "AKÇAKALE",
    "BİRECİK",
    "BOZOVA",
    "CEYLANPINAR",
    "EYYÜBİYE",
    "HALFETİ",
    "HALİLİYE",
    "HARRAN",
    "HİLVAN",
    "KARAKÖPRÜ",
    "SİVEREK",
    "SURUÇ",
    "VİRANŞEHİR",
  ],
  uşak: ["uşak", "BANAZ", "EŞME", "KARAHALLI", "SİVASLI", "ULUBEY"],
  van: [
    "BAHÇESARAY",
    "BAŞKALE",
    "ÇALDIRAN",
    "ÇATAK",
    "EDREMİT",
    "ERCİŞ",
    "GEVAŞ",
    "GÜRPINAR",
    "İPEKYOLU",
    "MURADİYE",
    "ÖZALP",
    "SARAY",
    "TUŞBA",
  ],
  yozgat: [
    "yozgat",
    "AKDAĞMADENİ",
    "AYDINCIK",
    "BOĞAZLIYAN",
    "ÇANDIR",
    "ÇAYIRALAN",
    "ÇEKEREK",
    "KADIŞEHRİ",
    "SARAYKENT",
    "SARIKAYA",
    "SORGUN",
    "ŞEFAATLİ",
    "YENİFAKILI",
    "YERKÖY",
  ],
  zonguldak: [
    "zonguldak",
    "ALAPLI",
    "ÇAYCUMA",
    "DEVREK",
    "EREĞLİ",
    "GÖKÇEBEY",
    "KİLİMLİ",
    "KOZLU",
  ],
  aksaray: [
    "aksaray",
    "AĞAÇÖREN",
    "ESKİL",
    "GÜLAĞAÇ",
    "GÜZELYURT",
    "ORTAKÖY",
    "SARIYAHŞİ",
    "SULTANHANI",
  ],
  bayburt: ["bayburt", "AYDINTEPE", "DEMİRÖZÜ"],
  karaman: [
    "karaman",
    "AYRANCI",
    "BAŞYAYLA",
    "ERMENEK",
    "KAZIMKARABEKİR",
    "SARIVELİLER",
  ],
  kırıkkale: [
    "kırıkkale",
    "BAHŞILI",
    "BALIŞEYH",
    "ÇELEBİ",
    "DELİCE",
    "KARAKEÇİLİ",
    "KESKİN",
    "SULAKYURT",
    "YAHŞİHAN",
  ],
  batman: ["batman", "BEŞİRİ", "GERCÜŞ", "HASANKEYF", "KOZLUK", "SASON"],
  şırnak: [
    "şırnak",
    "BEYTÜŞŞEBAP",
    "CİZRE",
    "GÜÇLÜKONAK",
    "İDİL",
    "SİLOPİ",
    "ULUDERE",
  ],
  bartın: ["bartın", "AMASRA", "KURUCAŞİLE", "ULUS"],
  ardahan: ["ardahan", "ÇILDIR", "DAMAL", "GÖLE", "HANAK", "POSOF"],
  ığdır: ["ığdır", "ARALIK", "KARAKOYUNLU", "TUZLUCA"],
  yalova: ["yalova", "ALTINOVA", "ARMUTLU", "ÇINARCIK", "ÇİFTLİKKÖY", "TERMAL"],
  karabük: ["karabük", "EFLANİ", "ESKİPAZAR", "OVACIK", "SAFRANBOLU", "YENİCE"],
  kilis: ["kilis", "ELBEYLİ", "MUSABEYLİ", "POLATELİ"],
  osmaniye: [
    "osmaniye",
    "BAHÇE",
    "DÜZİÇİ",
    "HASANBEYLİ",
    "KADİRLİ",
    "SUMBAS",
    "TOPRAKKALE",
  ],
  düzce: [
    "düzce",
    "AKÇAKOCA",
    "CUMAYERİ",
    "ÇİLİMLİ",
    "GÖLYAKA",
    "GÜMÜŞOVA",
    "KAYNAŞLI",
    "YIĞILCA",
  ],
};

const en2trCharMap: Record<string, string> = {
  i: "ı",
  o: "ö",
  s: "ş",
  g: "ğ",
  u: "ü",
  c: "ç",
};

export function convertEnglishSubPlaceNameToTurkish(
  city: string,
  subPlace: string
): string | false {
  const subPlaces = TurkeyMap[city.toLocaleLowerCase("tr")];
  if (!subPlaces) throw `City ${city} not found in Turkey Map`;
  subPlaces.push(city);

  for (let p of subPlaces) {
    if (areSubcityNamesEqual(subPlace, p)) {
      let str = p.toLocaleLowerCase("tr");
      str = str.charAt(0).toLocaleUpperCase("tr") + str.slice(1);
      return str;
    }
  }
  return false;
}

function areSubcityNamesEqual(enString: string, trString: string) {
  if (!enString || !trString) return false;
  if (enString.length !== trString.length) return false;
  const en = enString.toLocaleLowerCase("tr");
  const tr = trString.toLocaleLowerCase("tr");
  for (let i = 0; i < en.length; i++) {
    const enChar = en[i];
    const trChar = tr[i];
    if (enChar !== trChar && en2trCharMap[enChar] !== trChar) return false;
  }
  return true;
}
